[flavor]
use = "tokyo-night"
dark = "tokyo-night"

[indicator]
padding = { open = "▐", close = "▌" }

[tabs]
sep_inner = { open = "[", close = "]" }
sep_outer = { open = "", close = "" }

[status]
sep_left = { open = "", close = "]" }
sep_right = { open = "[", close = "" }

[mgr]
border_symbol = "│"
